apiVersion: apps/v1
kind: Deployment
metadata:
  name: addition-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: addition-api
  template:
    metadata:
      labels:
        app: addition-api
    spec:
      containers:
      - name: addition-api
        image: addition-api:latest
        ports:
        - containerPort: 5000