apiVersion: v1
kind: Service
metadata:
  name: multiplication-service
spec:
  selector:
    app: multiplication-api
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 5001
  type: LoadBalancer