apiVersion: apps/v1
kind: Deployment
metadata:
  name: multiplication-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multiplication-api
  template:
    metadata:
      labels:
        app: multiplication-api
    spec:
      containers:
      - name: multiplication-api
        image: multiplication-api:latest
        ports:
        - containerPort: 5001